name: Artillery Action to test endpoint function users-userId-tasks

on:
  push:
    # Action is called when a branch is merged with development
    branches:
      - development  

# Set up env variables for Node and Python
# Note: there is no Python functionality yet, but there will be eventually for uploadiing results to S3
env:
  NODE_VERSION: '14'  # the version of node we are using
  NPM_CONFIG_PREFIX: "~/.npm-global" # Required to set path for artillery call

jobs:
  artillery-test-users-user_id-tasks:
    # Create ubuntu VM for actions
    runs-on: ubuntu-latest 

    steps:
    #Checkout current repo
    - name: 'Checkout Repository GitHub Action' 
      uses: actions/checkout@v2

    #Setup Node
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        check-latest: true
    
    #Setup node package manager
    - name: 'Run npm init'
      run: npm init -y
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    #install artillery
    - name: Run npm install artillery  
      run: npm install -g artillery

    #Get current date for outputted file name
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H-%M-%S')"

    # Call artillery test located at ./test/artillery/artillery-perf-test-users-user_id-tasks.yaml
    # Return temp results to test/results/artillery-test-users-user_id-tasks-results.json
    - name: Run Artillery Test
      run: /home/runner/.npm-global/lib/node_modules/artillery/bin/artillery run --output test/results/artillery-test-users-user_id-tasks-results.json ./test/artillery/artillery-perf-test-users-user_id-tasks.yaml
      
    # Change results file name to follow naming conventions and include date/time  
    - name: Rename results json
      run: |
        cp test/results/artillery-test-users-user_id-tasks-results.json "test/results/artillery_${{ steps.date.outputs.date }}.json"
    
    # Upload the results to S3 bucket
    - name: AWS CLI S3
      run: |
        aws s3 cp test/results/ s3://artillery --recursive --exclude "*" --include "artillery*"
      
      
      
      
   
