name: Performance-Test

on:  
  push:
    branches:
      - development

jobs:
  slsart-perf:
    name: slsart Performance Test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      AWS_SLSART_REGION: "us-west-2"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install serverless and serverless-artillery
        run: |
          npm install -g serverless@1.38.0 serverless-artillery
      - name: Deploy, invoke, remove functions
        run: |
          ~/.npm-global/bin/slsart deploy --region $AWS_SLSART_REGION
          ~/.npm-global/bin/slsart invoke --region $AWS_SLSART_REGION
          ~/.npm-global/bin/slsart remove --region $AWS_SLSART_REGION
