name: sql injection test for users/userid/tasks post

on:
  push:
    branches:
      - development
env:
  NODE_VERSION: '10.x'
  TEST_CASE_BODY: "{\"title\": \"injection\", \"description\": \"'hacked'); DELETE FROM users WHERE userId > 1020; -- \"}"
  RESULT_FILE_PATH: ../../test/results/sql-injection-users-userid-tasks-post.json

jobs:
  POST-test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: create a test user
        run: |
          curl -v -X POST -d '{"firstName": "injection-user-test", "lastName": "injection-user-test", "email": "injection-user-test"}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users > test/security/sql-injection/sql-injection-users-userid-tasks-post.json
      - name: get userId
        id: userId
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: test/security/sql-injection/sql-injection-users-userid-tasks-post.json
          prop_path: 'userId'
      - name: "create a task for the created user id ${{steps.userId.outputs.prop}}"
        run: |
          curl -v -X POST -d '{"title": "sqlINJ", "description": "'oops'); DELETE FROM users WHERE userId > 1000; -- "}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/${{steps.userId.outputs.prop}}/tasks? > test/security/sql-injection/sql-injection-users-userid-tasks-post.json
      - name: read output
        id: taskId
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: test/security/sql-injection/sql-injection-users-userid-tasks-post.json
          prop_path: 'taskId'
      - name: "task created with id: ${{steps.taskId.outputs.prop}}"
        run: echo "task created with id:" ${{steps.taskId.outputs.prop}} 
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: 'test/security/sql-injection/sql-injection-users-userid-tasks-post.json'

